#
# Copyright (C) 2025 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

 OF_MAINTAINER := adontoo & nanya & good-name-awa
 
 #display for pad
 
 OF_SCREEN_DPI := 240  
 OF_OPTIONS_LIST_NUM := 4
 OF_USE_GREEN_LED := 0

 OF_ENABLE_ALL_PARTITION_TOOLS := 1
 OF_WORKAROUND_BACKUP_BUG := 1
 OF_USE_AIDL_BOOT_CONTROL := 1
 OF_FORCE_DATA_FORMAT_F2FS := 1
 OF_UNBIND_SDCARD_F2FS := 1
 OF_WIPE_METADATA_AFTER_DATAFORMAT := 1
 OF_DYNAMIC_FULL_SIZE := 14578294784
 OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
 OF_FORCE_PREBUILT_KERNEL := 1
 OF_NO_RELOAD_AFTER_DECRYPTION := 1
 OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
 OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
 OF_RECOVERY_AB_FULL_REFLASH_RAMDISK := 1

 OF_USE_LZ4_COMPRESSION := 1
 OF_ENABLE_FS_COMPRESSION := 1

